version: "3"

services:
    restaurant:
      build: 
        context: .
        dockerfile: Dockerfile
      environment: 
        - DATABASE_URI=sqlite:///restaurant.db
        - FLASK_RUN_HOST=0.0.0.0
        - FLASK_APP=restaurant/app.py
        - CELERY_BROKER_URL=redis://redis:6379
        - CELERY_BACKEND_URL=redis://redis:6379
        - PYTHONPATH=restaurant/
      ports:
        - "5000-5010:5000"
      networks:
        - default
      command: pytest restaurant/tests/ --cov=restaurant -s